#! /bin/sh
case "$1" in 
    start)
    echo "loading faulty,hello and scull driver"
    scull_load
    module_load faulty
    modprobe hello
    ;;
    stop)
    echo "unloading faulty,hello and scull driver"
    scull_unload
    module_unload faulty
    rmmod hello
    ;;
    *)
    echo "usage: $0 {start|stop}"
    exit 1
    esac
exit 0


